### ISSUE TITLE
Bug in Frida Script for FingerprintManager

### ISSUE THREAD

**Issue by sushi2k** [FSecureLABS/android-keystore-audit#3]
It was reported to us that one of the Frida scripts has a bug. The fix is described here:

https://github.com/OWASP/owasp-mstg/issues/1461#issuecomment-538473863

**Comment by deus-ex-silicium** [comment]
The bug should be fixed now, feel free to let us know if that is not the case, thanks.

**Comment by WarrDaddy** [comment]
Hello,

I'm experiencing this issue. I've added the variable to line 168 per d0n473ll0's recommendation however, the error is persistent.

line 168 per d0n473ll0's recommendation can be found at the link below
https://github.com/OWASP/owasp-mstg/issues/1461

**Comment by WarrDaddy** [comment]
![Screen Shot 2021-11-24 at 9 55 53 AM](https://user-images.githubusercontent.com/57737355/143290635-5b67b9d8-e7a5-48a8-9065-6634123fec91.png)
